version: "3.9"
services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
    image: notebookapp
    container_name: notebook-app
    environment:
      - JUPYTER_TOKEN=password
      - JUPYTER_ENABLE_LAB=yes
    # volumes:
    #   - .:/home/jovyan/app
    #   - ./notebooks:/home/jovyan/app
    #   - ./src:/home/jovyan/app
    ports:
      - 7777:8888
    networks:
      - osh888

networks:
  osh888:
